### PR TITLE
About window - fixes #77

### LINKED ISSUE #77: Attribution
Currently `(C) Charlie Lee 2015` is displayed in both the animator and menu windows. I have a 2 part question regarding this:

1) Is it standard for this information to be prominent in such a way, would it be better for it to be displayed in the menu window, not at all or on a separate about page?

2) Boats Animator is an open source project and this copyright attribution was added before I created this GitHub repository. Since there have been major contributions by others is saying that the program is `Copyright Charlie Lee` strictly no longer true and a bit inconsiderate to the other contributors?

Obviously this is an issue that would potentially be slightly awkward for anyone other than myself to bring up but I really want to make sure that I'm doing things properly and that the current and future contributors to BA get the credit they deserve.

### PR DESCRIPTION
**Pull request by BoatsAreRockable**
This PR add `Help > About Boats Animator` to the top menu. Doing so causes the following window to open:

screenshot 166

Additionally the copyright notice has been removed from the status bar (#77) and the dev tools link has been moved to be in its place.

### CODE REVIEW

**Comment by le717** [comment]
On mobile, can't review too well. Sorry in advance for the mess. 

About.js - remove unneeded file and news feed requires

**Comment by le717** [comment]
In adding the option to the menu: can you not just type `click: openAbout`? It should have the same effect. 

I really want to reduce that CSS duplication. Oh well. 

"HTML5, JavaScript,  and WebRTC"

I guess it looks OK. Unfortunately I can't test it right now (I'll try to test it or give an explanation soon, one).

**Comment by le717** [comment]
The dev and reload methods in about.js look unused. Remove them.

**Comment by BoatsAreRockable** [comment]
@le717 Opps... I've fixed that now! Also I've noticed there's several other menu options that need their click functions compacting but I'll sort that out separately

**Comment by le717** [comment]
:shipit:

**Pull request merged**
