### PR TITLE
Generalize sidebar toggle button (fix #1)

### LINKED ISSUE #1: Onion skin toggle is off center
This element in the sidebar is currently too high

### PR DESCRIPTION
**Pull request by le717**
It is not the cleanest solution, but it works. I also generalized the button styling so new ones can be added without too much hassle (more styling refactoring will be needed if/when more are added).

### CODE REVIEW

**Comment by BoatsAreRockable** [comment]
This PR has conflicts with my own recent commit. I shall manually add what you've changed now.

**Comment by le717** [comment]
No no, I can fix it. Give me a few minutes. :)

**Comment by BoatsAreRockable** [comment]
Alright then thank you as always :)

**Comment by le717** [comment]
PR can now be merged. And yes, I did a visual check, the button is now lined up. :)

**Pull request merged**
