### PR TITLE
Added mousetrap shortcuts to existing features

### PR DESCRIPTION
**Pull request by BoatsAreRockable**
Part of #91. I've also added the ability to begin playback from the 1st frame captured; this is particularly useful in playback mode. The other shortcuts I've implemented are checked off the list at #91.

In addition I've capitalised the menubar items' titles since I was already poking around with them.

I meant for this to be part of the 0.7.x series but I guess since this is ready it could go into 0.6.4.

### CODE REVIEW

**Comment by BoatsAreRockable** [comment]
@le717 This is ready for reviewing if possible :)

**Comment by BoatsAreRockable** [comment]
@le717 I've reverted 54b2e52.

**Comment by BoatsAreRockable** [comment]
NW.js 0.13 greatly improves its shortcut API. I think this should be redone using it.

**Comment by le717** [comment]
If this PR is closed, it should be removed from the milestone. ;)

**Pull request closed without merging**
