### PR TITLE
Break off changes from #22 - Part 3

### PR DESCRIPTION
**Pull request by le717**
Here it is

This PR includes
* The remaining changes from #22 (specifically, rewriting `takePicture()`)
* A complete rewrite of the frame reel, which brought about:
  * Individual frame deletion
  * Frame reel scrolling
  * Fixes for all issues listed in #4 

The frame reel rewrite is the new code here. While thinking how I could improve the frame reel and make it work with the revised capture code, I concluded that the wheel was reinvented. There were 5 hard-coded frame previews, each one's `src` updated with the newly captured frame. Scrolling was planned to be done by clicking the button and updating the individual `src`s, which was a very intensive, slow, and complicated process, not to mention compounded the ability to delete individual frames. A scroll bar was going be added by way of a an `input type="range"` which presented an interesting set of challenges (how does sliding it change the frame reel? How do you go about making sure the scroll amount increases/decreases with the number of captured frames?) All this, I concluded, was reinventing what the browser can already do.

So I ripped it all out and started from scratch. I decided the previews would be dynamically injected into the reel via a `<table>`. This immediately solved many issues. Frames could be added/removed at will without having to worry about rebuilding the whole thing or holes appearing. A "No captured frames available." message would be displayed when (obviously) nothing was captured. This also meant in the future the reel can be dynamically built when frames are imported.

I then wrapped the table in a set-width container and set it to show a scroll bar when that value was exceeded. This would let the browser manage the scrolling and give the user more fine-grained scrolling control.

Finally, I made the scrolling arrows do their thing by adjusting the `scrollLeft` value of the container, again letting the browser manage everything.

I did have to do some minor markup changes to make the reel have the correct height at all times (the majority of the HTML changes are simple re-indentation) because `float`-based layouts are a pain and a half and the whole app should probably be reworked to not use them so much (Flexbox, what I used for the frame reel and the cause of the HTML changes, would be an excellent base. I have not followed it myself (I probably will hopefully soon), but I hear http://flexbox.io is a good place to learn all the ins and outs of Flexbox).

There you have it! :smile:

### CODE REVIEW

**Comment by le717** [comment]
Oh snap, I just realized I forgot to restore the onion skin overlay. I will fix it, but it is still safe to merge this as-is. I don't want to keep these changes held up too much longer.

**Comment by BoatsAreRockable** [comment]
Thank you very much, the frame reel was certainly the area I was previously most unhappy with. I'll have a look into Flexbox.

**Comment by BoatsAreRockable** [comment]
I tested this out and it works fantastically :smile:

**Comment by le717** [comment]
I think it's time to revise the roadmap so there is a clear idea of what features are desired and when. :)

**Pull request merged**
