### PR TITLE
[DO NOT MERGE] Rewrite picture taking code

### PR DESCRIPTION
**Pull request by le717**
Well, not a total rewrite as in none of your original setup is present anymore, but enough of a rewrite that it affects the entire code base and is not yet complete (hence the do not merge title).

This a a huge reworking, cleaning up the functions, following best practices, making them a bit more general, and as a bonus, supports individual frame deletion :smile:. This conflicts with the other PRs and I'm sure some of your local code too, so once it is done a point will have to be made to merge it and ensure everything else still works.

I am putting it up already so you can see how it works ahead of time and so we can ask questions before it lands.

### TODO ###
- [ ] Deleting an individual frame makes the frame reel act weird
- [x]  Undoing the last frame does not display a blank image in the frame reel

### CODE REVIEW

**Comment by le717** [comment]
Since this is such a large change, you should probably proceed with your other changes (and maybe another alpha release, IDK) while I finalize it, then when it is complete I can see into merging the changes from `master` into this.

Also, if you get a chance to pull this locally, it does need _lots_ of testing to make sure everything still works as it should.

**Comment by BoatsAreRockable** [comment]
Released current source as 0.4.0. I must catch up on some sleep now but I will hopefully give this a test for issues tomorrow. 

Couple of questions:
* What are the lines starting with @param for? They appear some sort of documentation process
* I don't really understand the purpose of the `|` pipes in the notification code
* I'm rather confused by the usage of the `$` symbols in areas such as `function saveFrame()`

Sorry about all the questions... I am extremely appreciative of all the help you are giving me with this project, but even more so with what you have helped me to learn. Arguably it was probably rather foolish for someone of my ability of JavaScript to take on such a project but learning the practical way has definitely taught me far more than any book ever could.

I really owe to you for making this project work and making into something that one day genuinely could be used by stop motion animators.

**Comment by le717** [comment]
Do not feel bad about asking questions, I told you to ask! If you have a question about some code, ask away! Ask before you merge too, its all OK!

As for acting "foolish", I'd argue otherwise. While a book can help teach how the language works, some of the best experience comes from diving in head-first and making something. I have done that and probably will continue to do that. However, it really helps when someone more experienced is around that can help guide, show, and teach (no matter how annoying it may be at times). I know I wish I had had someone around to help me.

Now onto the questions.

> What are the lines starting with `@param` for? They appear some sort of documentation process

You are correct! They are [JSDoc](http://usejsdoc.org/) annotations. They help anyone reading the code or contributing know what kind of input/output (among other things) the function has so they can better under the code. 

> I don't really understand the purpose of the | pipes in the notification code

Double pipes in JavaScript are the "or" operator. Their purpose in the notification code is simple: if for some reason `msg` is a falsey value, instead of displaying `undefined` it changes the message to an empty string (so a blank message). It's essentially a default value for `msg`. Read those lines as so:

"Messages is message OR empty string if message is falsey"

> I'm rather confused by the usage of the $ symbols in areas such as function saveFrame()

So you know how in order to display a variable in a string you have to mess with all those quotes and plus signs? Well, in the newest JS revision there's a new thing called template strings. Among other thing, they allow you to make multi-line strings and interpolate  variables and expressions directly into a string. The syntax to do that is

Back tick The number is ${number}. Back tick

(I can't put the actual back tick until I'm on my laptop because GitHub will render that line as code.)

Template strings can't quite be used on websites yet (sadly), but since we are using NW.js (which a is a Chrome wrapper), we can use them all we want. For more details, check out this [excellent article] (http://davidwalsh.name/javascript-template-strings).

**Comment by BoatsAreRockable** [comment]
Thank you very much for that info :) I think I might have asked you about template strings before... They appear to be similar to the templates I've come across in Wiki code. The same can be said for or statements which feature heavily on wikis. 

For JSDoc annotations are they usually simply displayed in the code? Or do developers typically have a plugin that does something more with them in their IDE. I notice Brackets seems to highlight them in a particular way and I assume that's all you'd expect.

**Comment by le717** [comment]
For all intent and purpose this is "complete". Frame scrolling never worked anyway and would be out of scope to reimplement here. I am working on getting individual frame deletion to interact correctly with the frame reel but it is a doosey. You can go ahead and start testing this now. Be sure to test:

* New picture
* Undo frame
* Frame saving
* Take frames, undo, take more, undo, ensure proper frame was deleted (test multiple times with various numbers of frames)
* Individual frame deletion (ignore the frame reel, make sure the proper frame was removed from the HDD)
* Onion skinning has the correct preview frame
* Status bar displays correct values
* Can't undo when no frames are present
* Take frames, single delete one, take more (ensure continued ordering from last frame taken)
* Extend above by undoing after taking more
* No camera attacted = clear canvas message in console

**Comment by BoatsAreRockable** [comment]
Testing, will tick as I complete checks:
- [ ] New picture
- [ ] Undo frame
- [ ] Frame saving
- [ ] Take frames, undo, take more, undo, ensure proper frame was deleted (test multiple times with various numbers of frames)
- [ ] Individual frame deletion (ignore the frame reel, make sure the proper frame was removed from the HDD)
- [ ] Onion skinning has the correct preview frame
- [ ] Status bar displays correct values
- [ ] Can't undo when no frames are present
- [ ] Take frames, single delete one, take more (ensure continued ordering from last frame taken)
- [ ] Extend above by undoing after taking more
- [ ] No camera attached = clear canvas message in console

**Comment by BoatsAreRockable** [comment]
Issues:
* Playback does not appear to have been reimplemented  yet
* After deleting a frame via the frame reel the onion skinning frame does not update
   EDIT:

**Comment by le717** [comment]
Playback?! I didn't touch that code and didn't think I touched anything that would affect it. Oh well. :(

**Comment by le717** [comment]
OK, so this PR is really big (already 20 commits). I may end up breaking it up and submitting smaller parts in other PRs so these changes don't come in all at once and make everything easier to test. IDK if I will yet but I am thinking about it.

**Comment by le717** [comment]
I haven't forgotten about this. I have been working on some additional code to tie up the loose ends. And since I've split off 2/3rd of this PR, I am going to close this and submit a different PR with the remaining + new changes. Sound good to you? :)

**Comment by BoatsAreRockable** [comment]
Sounds fine, thank you for your continued assistance

**Comment by le717** [comment]
> For JSDoc annotations are they usually simply displayed in the code? Or do developers typically have a plugin that does something more with them in their IDE. I notice Brackets seems to highlight them in a particular way and I assume that's all you'd expect.

I forgot to reply to this.

Usually they are just displayed. For libraries, there is a utility that parses them and generates HTML for public documentation (which is not of use to us). Brackets just highlights the block comments, AFAIK there is no special JSDoc highlighting.

Since you are using Brackets, I recommend you install [Show Whitespace](https://github.com/DennisKehrig/brackets-show-whitespace). Use the build from the git repo (the registry version is highly out-of-date). You'll wonder how you ever coded without it.

**Pull request closed without merging**
